packages:
  - frontend/web
  - frontend/core
  - frontend/app
catalog:
  react: ^18.0.0
  react-dom: ^18.0.0
  '@types/react': ^18.0.0
  '@types/react-dom': ^18.0.0
  typescript: ^5.8.3
  vite: ^5.0.0
  vite-plugin-svgr: ^4.3.0
  '@tailwindcss/vite': ^4.1.3
  tailwindcss: ^4.1.3
  '@vitejs/plugin-react-swc': ^3.5.0
  '@tanstack/router-plugin': ^1.114.13
  '@tanstack/router-cli': ^1.114.13
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
