packages:
  - "frontend/web"
  - "frontend/core"
  - "frontend/app"
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
  - msw

catalog:
  react: ^18.0.0
  react-dom: ^18.0.0
  typescript: ^5.8.3
  vite: ^5.0.0
  vite-plugin-svgr: ^4.3.0
  '@tailwindcss/vite': ^4.1.3
  '@vitejs/plugin-react': ^4.3.4
  '@tanstack/router-plugin': ^1.114.13