packages:
  - frontend/web
  - frontend/core
  - frontend/app/shared
  - frontend/app/windows
  - frontend/app/android
  - frontend/design-tokens
  - sites

catalog:
  '@tailwindcss/vite': ^4.1.3
  '@tanstack/router-cli': ^1.136.5
  '@tanstack/router-plugin': ^1.136.5
  '@types/react': ^18.0.0
  '@types/react-dom': ^18.0.0
  '@vitejs/plugin-react-swc': ^3.5.0
  react: ^18.0.0
  react-dom: ^18.0.0
  tailwindcss: ^4.1.3
  typescript: ^5.8.3
  vite: ^5.4.21
  vite-plugin-svgr: ^4.3.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
