/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuestRouteImport } from './routes/guest/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as GuestRegisterImport } from './routes/guest/register'
import { Route as GuestLoginImport } from './routes/guest/login'
import { Route as GuestForgotPasswordImport } from './routes/guest/forgot-password'
import { Route as GuestConfirmPasswordImport } from './routes/guest/confirm-password'
import { Route as AuthTasksImport } from './routes/auth/tasks'
import { Route as AuthTagsImport } from './routes/auth/tags'
import { Route as AuthStatisticsImport } from './routes/auth/statistics'
import { Route as AuthPreferencesImport } from './routes/auth/preferences'
import { Route as AuthLogsImport } from './routes/auth/logs'
import { Route as GuestVerifyEmailIndexImport } from './routes/guest/verify-email/index'
import { Route as GuestVerifyEmailTokenImport } from './routes/guest/verify-email/$token'
import { Route as GuestResetPasswordTokenImport } from './routes/guest/reset-password.$token'

// Create/Update Routes

const GuestRouteRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuestRegisterRoute = GuestRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRouteRoute,
} as any)

const GuestLoginRoute = GuestLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)

const GuestForgotPasswordRoute = GuestForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)

const GuestConfirmPasswordRoute = GuestConfirmPasswordImport.update({
  id: '/confirm-password',
  path: '/confirm-password',
  getParentRoute: () => GuestRouteRoute,
} as any)

const AuthTasksRoute = AuthTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthTagsRoute = AuthTagsImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthStatisticsRoute = AuthStatisticsImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthPreferencesRoute = AuthPreferencesImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLogsRoute = AuthLogsImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthRouteRoute,
} as any)

const GuestVerifyEmailIndexRoute = GuestVerifyEmailIndexImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => GuestRouteRoute,
} as any)

const GuestVerifyEmailTokenRoute = GuestVerifyEmailTokenImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => GuestRouteRoute,
} as any)

const GuestResetPasswordTokenRoute = GuestResetPasswordTokenImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => GuestRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/logs': {
      id: '/auth/logs'
      path: '/logs'
      fullPath: '/auth/logs'
      preLoaderRoute: typeof AuthLogsImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/preferences': {
      id: '/auth/preferences'
      path: '/preferences'
      fullPath: '/auth/preferences'
      preLoaderRoute: typeof AuthPreferencesImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/statistics': {
      id: '/auth/statistics'
      path: '/statistics'
      fullPath: '/auth/statistics'
      preLoaderRoute: typeof AuthStatisticsImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/tags': {
      id: '/auth/tags'
      path: '/tags'
      fullPath: '/auth/tags'
      preLoaderRoute: typeof AuthTagsImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/tasks': {
      id: '/auth/tasks'
      path: '/tasks'
      fullPath: '/auth/tasks'
      preLoaderRoute: typeof AuthTasksImport
      parentRoute: typeof AuthRouteImport
    }
    '/guest/confirm-password': {
      id: '/guest/confirm-password'
      path: '/confirm-password'
      fullPath: '/guest/confirm-password'
      preLoaderRoute: typeof GuestConfirmPasswordImport
      parentRoute: typeof GuestRouteImport
    }
    '/guest/forgot-password': {
      id: '/guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/guest/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordImport
      parentRoute: typeof GuestRouteImport
    }
    '/guest/login': {
      id: '/guest/login'
      path: '/login'
      fullPath: '/guest/login'
      preLoaderRoute: typeof GuestLoginImport
      parentRoute: typeof GuestRouteImport
    }
    '/guest/register': {
      id: '/guest/register'
      path: '/register'
      fullPath: '/guest/register'
      preLoaderRoute: typeof GuestRegisterImport
      parentRoute: typeof GuestRouteImport
    }
    '/guest/reset-password/$token': {
      id: '/guest/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/guest/reset-password/$token'
      preLoaderRoute: typeof GuestResetPasswordTokenImport
      parentRoute: typeof GuestRouteImport
    }
    '/guest/verify-email/$token': {
      id: '/guest/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/guest/verify-email/$token'
      preLoaderRoute: typeof GuestVerifyEmailTokenImport
      parentRoute: typeof GuestRouteImport
    }
    '/guest/verify-email/': {
      id: '/guest/verify-email/'
      path: '/verify-email'
      fullPath: '/guest/verify-email'
      preLoaderRoute: typeof GuestVerifyEmailIndexImport
      parentRoute: typeof GuestRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthLogsRoute: typeof AuthLogsRoute
  AuthPreferencesRoute: typeof AuthPreferencesRoute
  AuthStatisticsRoute: typeof AuthStatisticsRoute
  AuthTagsRoute: typeof AuthTagsRoute
  AuthTasksRoute: typeof AuthTasksRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLogsRoute: AuthLogsRoute,
  AuthPreferencesRoute: AuthPreferencesRoute,
  AuthStatisticsRoute: AuthStatisticsRoute,
  AuthTagsRoute: AuthTagsRoute,
  AuthTasksRoute: AuthTasksRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestConfirmPasswordRoute: typeof GuestConfirmPasswordRoute
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestResetPasswordTokenRoute: typeof GuestResetPasswordTokenRoute
  GuestVerifyEmailTokenRoute: typeof GuestVerifyEmailTokenRoute
  GuestVerifyEmailIndexRoute: typeof GuestVerifyEmailIndexRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestConfirmPasswordRoute: GuestConfirmPasswordRoute,
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestResetPasswordTokenRoute: GuestResetPasswordTokenRoute,
  GuestVerifyEmailTokenRoute: GuestVerifyEmailTokenRoute,
  GuestVerifyEmailIndexRoute: GuestVerifyEmailIndexRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/auth/logs': typeof AuthLogsRoute
  '/auth/preferences': typeof AuthPreferencesRoute
  '/auth/statistics': typeof AuthStatisticsRoute
  '/auth/tags': typeof AuthTagsRoute
  '/auth/tasks': typeof AuthTasksRoute
  '/guest/confirm-password': typeof GuestConfirmPasswordRoute
  '/guest/forgot-password': typeof GuestForgotPasswordRoute
  '/guest/login': typeof GuestLoginRoute
  '/guest/register': typeof GuestRegisterRoute
  '/guest/reset-password/$token': typeof GuestResetPasswordTokenRoute
  '/guest/verify-email/$token': typeof GuestVerifyEmailTokenRoute
  '/guest/verify-email': typeof GuestVerifyEmailIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/auth/logs': typeof AuthLogsRoute
  '/auth/preferences': typeof AuthPreferencesRoute
  '/auth/statistics': typeof AuthStatisticsRoute
  '/auth/tags': typeof AuthTagsRoute
  '/auth/tasks': typeof AuthTasksRoute
  '/guest/confirm-password': typeof GuestConfirmPasswordRoute
  '/guest/forgot-password': typeof GuestForgotPasswordRoute
  '/guest/login': typeof GuestLoginRoute
  '/guest/register': typeof GuestRegisterRoute
  '/guest/reset-password/$token': typeof GuestResetPasswordTokenRoute
  '/guest/verify-email/$token': typeof GuestVerifyEmailTokenRoute
  '/guest/verify-email': typeof GuestVerifyEmailIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/auth/logs': typeof AuthLogsRoute
  '/auth/preferences': typeof AuthPreferencesRoute
  '/auth/statistics': typeof AuthStatisticsRoute
  '/auth/tags': typeof AuthTagsRoute
  '/auth/tasks': typeof AuthTasksRoute
  '/guest/confirm-password': typeof GuestConfirmPasswordRoute
  '/guest/forgot-password': typeof GuestForgotPasswordRoute
  '/guest/login': typeof GuestLoginRoute
  '/guest/register': typeof GuestRegisterRoute
  '/guest/reset-password/$token': typeof GuestResetPasswordTokenRoute
  '/guest/verify-email/$token': typeof GuestVerifyEmailTokenRoute
  '/guest/verify-email/': typeof GuestVerifyEmailIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guest'
    | '/auth/logs'
    | '/auth/preferences'
    | '/auth/statistics'
    | '/auth/tags'
    | '/auth/tasks'
    | '/guest/confirm-password'
    | '/guest/forgot-password'
    | '/guest/login'
    | '/guest/register'
    | '/guest/reset-password/$token'
    | '/guest/verify-email/$token'
    | '/guest/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guest'
    | '/auth/logs'
    | '/auth/preferences'
    | '/auth/statistics'
    | '/auth/tags'
    | '/auth/tasks'
    | '/guest/confirm-password'
    | '/guest/forgot-password'
    | '/guest/login'
    | '/guest/register'
    | '/guest/reset-password/$token'
    | '/guest/verify-email/$token'
    | '/guest/verify-email'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/guest'
    | '/auth/logs'
    | '/auth/preferences'
    | '/auth/statistics'
    | '/auth/tags'
    | '/auth/tasks'
    | '/guest/confirm-password'
    | '/guest/forgot-password'
    | '/guest/login'
    | '/guest/register'
    | '/guest/reset-password/$token'
    | '/guest/verify-email/$token'
    | '/guest/verify-email/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/guest"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/logs",
        "/auth/preferences",
        "/auth/statistics",
        "/auth/tags",
        "/auth/tasks"
      ]
    },
    "/guest": {
      "filePath": "guest/route.tsx",
      "children": [
        "/guest/confirm-password",
        "/guest/forgot-password",
        "/guest/login",
        "/guest/register",
        "/guest/reset-password/$token",
        "/guest/verify-email/$token",
        "/guest/verify-email/"
      ]
    },
    "/auth/logs": {
      "filePath": "auth/logs.tsx",
      "parent": "/auth"
    },
    "/auth/preferences": {
      "filePath": "auth/preferences.tsx",
      "parent": "/auth"
    },
    "/auth/statistics": {
      "filePath": "auth/statistics.tsx",
      "parent": "/auth"
    },
    "/auth/tags": {
      "filePath": "auth/tags.tsx",
      "parent": "/auth"
    },
    "/auth/tasks": {
      "filePath": "auth/tasks.tsx",
      "parent": "/auth"
    },
    "/guest/confirm-password": {
      "filePath": "guest/confirm-password.tsx",
      "parent": "/guest"
    },
    "/guest/forgot-password": {
      "filePath": "guest/forgot-password.tsx",
      "parent": "/guest"
    },
    "/guest/login": {
      "filePath": "guest/login.tsx",
      "parent": "/guest"
    },
    "/guest/register": {
      "filePath": "guest/register.tsx",
      "parent": "/guest"
    },
    "/guest/reset-password/$token": {
      "filePath": "guest/reset-password.$token.tsx",
      "parent": "/guest"
    },
    "/guest/verify-email/$token": {
      "filePath": "guest/verify-email/$token.tsx",
      "parent": "/guest"
    },
    "/guest/verify-email/": {
      "filePath": "guest/verify-email/index.tsx",
      "parent": "/guest"
    }
  }
}
ROUTE_MANIFEST_END */
