//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::decopon_sessions::Entity as DecoponSessions;
pub use super::log_tag::Entity as LogTag;
pub use super::logs::Entity as Logs;
pub use super::tag_task::Entity as TagTask;
pub use super::tags::Entity as Tags;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
