name: Deploy as demo version

on:
  push:
    branches:
      - deploy-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
      # Node.js環境のセットアップとnpmビルド
      - name: Set up Node.js and install dependencies
      # Viteのimport.metaはビルド時の変数を展開するため、
      # この段階で .envを作成する
        env: 
          VITE_APP_NAME: Decopon
          VITE_APP_ENV: demo
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # PHP依存関係のインストール（Composer）
      - name: Set up PHP and install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # プロジェクトに合わせたPHPバージョンを指定
      - run: composer install --no-dev --optimize-autoloader

      # サーバーにビルド済みアプリケーションを転送
      - name: Deploy to Lightsail
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          # SSH設定を準備
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # ホストキー検証をスキップ
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # ビルド済みのアプリケーションを転送
          rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete \
            --rsync-path="sudo rsync" \
            --exclude=".env" \
            --exclude="node_modules" \
            --exclude=".git" \
            ./ $DEPLOY_USER@$DEPLOY_SERVER:/var/www/html/decopon

          # サーバー上での設定とデプロイ
          ssh $DEPLOY_USER@$DEPLOY_SERVER << EOF
            sudo chown -R ec2-user:ec2-user /var/www/html/decopon
            sudo chown -R ec2-user:ec2-user /var/www/html/decopon/bootstrap/cache
            sudo chown -R ec2-user:ec2-user /var/www/html/decopon/storage
            sudo chmod -R 775 /var/www/html/decopon/bootstrap/cache
            sudo chmod -R 775 /var/www/html/decopon/storage
            cd /var/www/html/decopon
            php artisan migrate --force
            php artisan db:seed --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart nginx # 必要に応じてサーバー再起動
          EOF
